<MetaKey@MDLabel>:
    size_hint_x: 0.4
    halign: 'right'
    font_size: '9pt'
    color: 'b0b0b0'

<MetaValue@MDLabel>:
    size_hint_x: 0.6
    halign: 'left'
    font_size: '9pt'
    color: 'e0e0e0'

<MetaInfo>:
    orientation: 'horizontal'
    size_hint_y: None
    height: dp(20)

    MetaKey:
        id: key
        text: root.key
    
    MetaValue:
        id: value
        text: root.value
